### ISSUE TITLE
Can't get the other side of connection

### ISSUE THREAD

**Issue by knyttl** [scribu/wp-posts-to-posts#457]
Hi,

I can easily get one side fo connection as follows:

```
$connected = new WP_Query(array(
  'connected_type' => 'book_to_writer',
  'connected_items' => $writerId,
  'nopaging' => true,
));
```

But once I try to fetch by $bookId as:

```
$connected = new WP_Query(array(
  'connected_type' => 'book_to_writer',
  'connected_items' => $bookId,
  'nopaging' => true,
));
```

It always returns empty result. Definition is as follows:

```
p2p_register_connection_type(array(
    'name'        => $id,
    'from'        => 'writer',
    'to'          => 'book',
    'admin_box' => array(
        'show'    => 'from',
        'context' => 'advanced'
    )
));
```

It seems to me, that it looks for ids ONLY BY the `from` side of the connection.

**Comment by MoiseScalzo** [comment]
Hello Scribu I have a similar problem...
I had a connection type like
<code>
	p2p_register_connection_type( array(
		                              'name'        => 'type1_to_type2',
		                              'from'        => 'type1',
		                              'to'          => 'type2',
		                              'cardinality' => 'one-to-many'
	                              ) );
</code>

I can easily get back the related post (dicastero) in single.php (type1) with
<code>
			$posts = new WP_Query( array(
				                       'connected_type'  => type1_to_type2,
				                       'connected_items' =>get_queried_object(),
				                       'nopaging'        => true,
			                       ) );
</code>

Bug how if I'm seeing the inverse post and get the related post?

So what I need is if I'm seeing the type1 post I want to get back the type2 and vice-versa without rewrite the WP_Query, is it possibile?

**Comment by magicworks** [comment]
I found that function <code>each_connected</code> does this, you just have to give it an array containing post object instead of post object himself.
