### ISSUE TITLE
Listing related post types (schema not actual posts)

### ISSUE THREAD

**Issue by unstoppablecarl** [scribu/wp-posts-to-posts#468]
Is there a better way to do this? 

``` php
<?php
    function getRelatedPostTypes($postType){
        $connections = P2P_Connection_Type_Factory::get_all_instances();
        $related = [];
        foreach($connections as $connection){
            $fromPostType = $connection->side['from']->query_vars['post_type'][0];
            if($fromPostType === $postType){
                $related[] = $connection->side['to']->query_vars['post_type'][0];
            }
        }
        return $related;
    }
```

**Comment by MoiseScalzo** [comment]
Hey guys thank you very much for this function, but, in my case, the unstoppablecarl's functions return always an empty array :(

**Comment by unstoppablecarl** [comment]
Make sure you are checking after those values get populated. I would need to see your code to help.

**Comment by MoiseScalzo** [comment]
If I call back your function from the front end (ex. single.php) it work great but if I calling it from the backend (ex. wp-admin/post.php) it return an empty array...I'm working directly from a custom Theme so normally the function.php file is loaded after all plugins...so why from the front end I can use the static method <code>P2P_Connection_Type_Factory::get_all_instances(); </code> but from the backend I can't? :(

**Comment by unstoppablecarl** [comment]
I think the data is populated after the load all plugins step. How are you hooking into the admin post page?

**Comment by MoiseScalzo** [comment]
I'm just calling it if global $pagenow == post.php because I need to get the list in the edit post page.

**Comment by unstoppablecarl** [comment]
where is that code exactly?

**Comment by MoiseScalzo** [comment]
in a require_once file called in the functions.php

**Comment by unstoppablecarl** [comment]
It should be inside of an action callback.

**Comment by MoiseScalzo** [comment]
I solved with a custom query:
<pre>
function get_related_post_type($postID) {

	global $wpdb;

	$query = "SELECT *
			FROM `cdm_wp_p2p`
			WHERE `cdm_wp_p2p`.`p2p_from` = '$postID'";

	$reults = $wpdb->get_results($query);

	$related     = [ ];

	foreach ( $reults as $connection ) {

		$to = $connection->p2p_to;
		$related[] = get_post_type($to);

	}

	$related = array_unique($related);
	$related = array_filter($related);

	return $related;

}
</pre>

I have to do some tests, but it seems to work
