### ISSUE TITLE
Please provide better documentation of how to use the Javascript API

### ISSUE THREAD

**Issue by rfair404** [scribu/wp-posts-to-posts#473]
Scribu - Love the p2p plugin - I have used it on a handful of projects, and enjoy using it. I am trying to extend the admin boxes using js and got a little bit lost on the js api. Is it possible to enhance the wiki documentation to explain what the API is and isn't intended for? Specifically, how to bind to a "connection" and how to trigger a connection meta and ordering update without needing to submit the post form. Thanks!

**Comment by scribu** [comment]
I've added a few more explanations to the wiki page: https://github.com/scribu/wp-posts-to-posts/wiki/Javascript-API

> trigger a connection meta and ordering update without needing to submit the post form

To do that, besides using the JavaScript API, you would also need to implement a custom ajax handler on the PHP side.
