### ISSUE TITLE
Can't modify p2p:per_page in get_related()

### ISSUE THREAD

**Issue by TweetPressFr** [scribu/wp-posts-to-posts#476]
Hi thanks for your great plugin. 

Currently there is no easy way to change p2p:per_page in the get_related() method (which is very handy by the way). I need to set this param so basically I copy your code in my own method and I redefine  `$extra_qv['p2p:per_page']  to the number I want. 

That would be cool to add a filter or a `wp_parse_args()`.

What do you think about that ?

Kind regards.

**Comment by scribu** [comment]
If you enable pagination for the first `get_connected()` call, you will get incorrect results. Full explanation here: https://github.com/scribu/wp-lib-posts-to-posts/commit/463d3d1661c226d6f15a8b7ce861021450919529

**Comment by TweetPressFr** [comment]
Thanks for the quick answer, in fact I was refering the second `get_connected()`my bad it's `$additional_qv`. This looks tricky. Currently I can tweak this but I get a notice I don't fully understand 
`undefined index 0`which is due to an empty array with flip_direction().

**Comment by TweetPressFr** [comment]
Solved this by passing arbitrary "thing" to `flip_direction()`. Seems to work with anything like string or object. I was told that it's because the method does not actually take any parameter but I can pass whatever I want to prevent empty array and then PHP notice.
