### ISSUE TITLE
Uninstalling data lose

### ISSUE THREAD

**Issue by PatelUtkarsh** [scribu/wp-posts-to-posts#479]
Hey scribu, 

One of my plugin [rtbiz](https://github.com/rtCamp/rtbiz) is dependent on your posts to posts plugin, We give user admin notice and let user install dependency but what happens is they don't read notice most of the time and press install and when they see posts to posts plugin on their plugins they try to delete it. Now when they delete posts to posts all the connection data is lose.

>Can we add filter of some kind that also let other plugin decide whether to delete DB table or not ? 

I have notice post to post register uninstall hook every time shouldn't be it on plugin active only ?

**Comment by scribu** [comment]
Have you considered using [lib-posts-to-posts](https://github.com/scribu/wp-lib-posts-to-posts) instead? It wouldn't show up in the plugins list and it doesn't have any uninstall code.

Note that the library doesn't contain any admin UI.

**Comment by PatelUtkarsh** [comment]
Yes just came across it after creating PR. 

Thank you for you time closing issue.
