### ISSUE TITLE
Class 'Mustache_Cache_NoopCache' not found

### ISSUE THREAD

**Issue by JayWood** [scribu/wp-posts-to-posts#482]
Got this today.  Updated to 1.6.4 yesterday.

https://gist.github.com/JayWood/0318882f17ae02c13732

**Comment by scribu** [comment]
What version did you upgrade from?

Did you upgrade using git? If so, did you remember to run `composer install`? More info: https://github.com/scribu/wp-posts-to-posts/blob/master/CONTRIBUTING.md#setup

**Comment by JayWood** [comment]
@scribu I upgraded via git, running composer fixes this, closing.  Please update your read me asking to do this, if it is already there, please excuse my ignorance :D

**Comment by scribu** [comment]
Cool.

It's not mentioned in the readme because it would show up on wordpress.org, where users don't need to use Composer. It is mentioned in the [contributor guide](https://github.com/scribu/wp-posts-to-posts/blob/master/CONTRIBUTING.md), though.

**Comment by dylanfisher** [comment]
I installed this plugin via wordpress.org, and I track my plugins directory with git. I get this error every time I push and pull the plugin to a different machine. Is it possible to avoid this?
