### ISSUE TITLE
Version 1.6.4 Mustache changes cause incompatibility

### ISSUE THREAD

**Issue by hkrutzer** [scribu/wp-posts-to-posts#487]
Hi,

We recently updated this plugin to 1.6.4 from 1.6.3 on a website that uses its own version of the Mustache library. 1.6.3 contains this code:
```php
		if ( !class_exists( 'Mustache' ) )
			require dirname(__FILE__) . '/../mustache/Mustache.php';
```
which ensured our version of Mustache was used.

In 1.6.4 the Mustache autoloader is always required, meaning we have to use the Mustache version that ships with this plugin, so we can't update our version of Mustache independently anymore and we have to update to a new version of Mustache whenever this plugin updates Mustache.

Neither situation is ideal; the best solution would be having this plugin use its version of Mustache and have our website use the version we specify, but this is not possible as classes can't be redeclared.

However, we'd prefer to have control over the Mustache version, with the mechanism used in 1.6.3.
This way we can lock it in our composer lockfile and ensure there will be no sudden incompatibility.

How do you feel about this?
I'm also willing to make any changes and submit a pull request.

**Comment by scribu** [comment]
The thing is that the new version of Mustache doesn't have a `Mustache` class anymore, so just checking

**Comment by scribu** [comment]
The thing is that the new version of Mustache doesn't have a `Mustache` class anymore, so just checking   for its existence isn't enough. To see what I mean, have a look at `admin/mustache.php`.

**Comment by scribu** [comment]
Actually, I think this solves the problem: since the new Mustache version doesn't define a `Mustache` class, you can have both versions running at the same time.

**Comment by hkrutzer** [comment]
What if another plugin uses the same version of the library though?
