### ISSUE TITLE
Isn't working on 4.3.1?

### ISSUE THREAD

**Issue by davesnx** [scribu/wp-posts-to-posts#497]
Hello @scribu @c10b10 

I just updated the version of WP to 4.3.1 and I found that doesn't load properly the `post.php?post=X&action=edit`, I mean the new/edit Post.

I'm not pretty sure that it was the plugin itself or the "settings". 

```
function my_connection_types()
{
    p2p_register_connection_type([
        'name' => 'posts_to_posts',
        'admin_box' => 'to',
        'from' => 'post',
        'to' => 'post',
        'reciprocal' => false
    ]);
}

add_action( 'p2p_init', 'my_connection_types' );
```

**Comment by mattrepublic** [comment]
It's something with the logic check I assume... `p2p_type` fails but `p2p_create_connection` works.
