### ISSUE TITLE
WP-CLI 'p2p' command does not work as command.php is not loaded

### ISSUE THREAD

**Issue by caseypatrickdriscoll** [scribu/wp-posts-to-posts#504]
![wp-cli-not-registered](https://cloud.githubusercontent.com/assets/870645/10671168/2efeba4c-78b7-11e5-9c66-8568ec8b2b5c.png)

If I add a simple `include 'command.php';` in `posts-to-posts.php` it works just fine with WP-CLI.

Not sure if I'm missing something here, or if you want to include command.php some other way. Will be sending in a PR in a minute.

**Comment by scribu** [comment]
`command.php` is loaded from `debug.php`: https://github.com/scribu/wp-posts-to-posts/blob/master/debug.php#L10-L11

I guess I just forgot to move it once the command became generally useful.
