### ISSUE TITLE
reciprocal are not sorable

### ISSUE THREAD

**Issue by twentyfortysix** [scribu/wp-posts-to-posts#512]
hello

here is my definition
```
function releated_connection(){
	p2p_register_connection_type(
	array(
		 'name' => 'page2page',
        'from' => 'page',
        'to' => 'page',
        'sortable' => 'any',
        'reciprocal' => true,
    	'title' => 'Relevant pages'
	)
	);
}
```
WordPress 4.3.1, P2P Version 1.6.5

if I comment out reciprocal, the drag&drop sorting works as expected, when both "reciprocal" and "sortable" are defined, the sorting does not work.
(no error in javascript console)

**Comment by wgroenewold** [comment]
"Note that ordering is not available for indeterminate connection types".
https://github.com/scribu/wp-posts-to-posts/wiki/Connection-ordering
