### ISSUE TITLE
Remove metabox from edit screen

### ISSUE THREAD

**Issue by rahilwazir** [scribu/wp-posts-to-posts#531]
I'm trying to remove the p2p connection metabox from one of the post type screen `product`

```
p2p_register_connection_type(array(
    'name' => 'related_post_to_product',
    'from' => 'post',
    'to' => 'product',
    'title' => array('from' => 'Related Products', 'to' => 'Related Articles'),
    'to_labels' => array(
        'create' => __('Assign Related Products')
    ),
    'from_query_vars' => array('post_status' => 'any')
));
```

Currently it displays both on `post` and `product` edit screen, how can I hide only for `product` post type?

I have tried:

```
function remove_metaboxes() {
    remove_meta_box('p2p-to-related_post_to_product', 'product', 'side');
    // Also tried id => related_post_to_product
}
add_action('admin_menu', 'remove_metaboxes');
```

But it doesn't work. Also increasing/decreasing priority doesn't help.

**Comment by Lumieredelune** [comment]
in the args of the connexion, add : 
`'reciprocal'	=> false,`

**Comment by rahilwazir** [comment]
@Lumieredelune Thanks, I fixed it by adding

    'admin_box' => 'from',

It renders metabox on the `from` relation which is `post`
