### ISSUE TITLE
Progamatically set connections between actual posts. Possible?

### ISSUE THREAD

**Issue by shmulim** [scribu/wp-posts-to-posts#537]
I'm digging through the documentation in search for a way to register connections between actual posts and not just between post types. Is there some kind of `set_connected()` or `set_related()` method , just like you can `get_connected()` or `get_related()`? I'm trying to create a user-facing form to create a post and connect it to another post. Can this be done with the current API?

**Comment by chrisgherbert** [comment]
Is this what you're looking for? [ https://github.com/scribu/wp-posts-to-posts/wiki/Creating-connections-programmatically]( https://github.com/scribu/wp-posts-to-posts/wiki/Creating-connections-programmatically)

**Comment by shmulim** [comment]
Thanks, that's it! :)
